(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-6',
          componentName:'@widget/CONTACT/bs-Component',
          props:props,
          context:context,
          contextKey:'context-bs-5',
          radpack:"@widget/CONTACT/bs-Component"
        });
      })({"structuredHours":[{"hour":{"day":"lunes","dayOfWeek":1,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"martes","dayOfWeek":2,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"miércoles","dayOfWeek":3,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"jueves","dayOfWeek":4,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"viernes","dayOfWeek":5,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"sábado","dayOfWeek":6,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":true}},{"hour":{"day":"domingo","dayOfWeek":0,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":true}}],"staticContent":{"today":"Hoy","submitButtonLoadingLabel":"Enviando","contactFormResponseErrorMessage":"Hubo un problema al intentar enviar tu mensaje; vuelve a intentarlo más tarde","phoneValidationErrorMessage":"Ingresa un número de teléfono válido.","defaultCancelButtonLabel":"Cancelar","byAppointment":"Cita previa","defaultSubmitButtonLabel":"Enviar","unsupportedFileType":"Tipo de archivo no compatible","maxFileCountLimit":"Solo se permiten {0} archivos.","closed":"Cerrado","attachments":"Datos adjuntos","termsOfSerivce":"Términos de servicio","attachFiles":"Adjuntar archivos","recaptchaDisclosure":"Este sitio está protegido por reCaPTCHA y aplican las {privacyPolicy} y los {termsOfSerivce} de Google.","emailValidationErrorMessage":"Favor de registrar una dirección de correo electrónico verdadera.","mapCTA":"Consigue las instrucciones","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Llena este campo obligatorio","openToday":"Abre hoy","couldNotAttach":"No fue posible adjuntar el siguiente archivo o los siguientes archivos","totalFileSizeLimit":"El total de los archivos excede el límite de {0}","privacyPolicy":"Política de privacidad","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms","fileSizeLimit":"El archivo excede el límite de {0}","emailMaxCountValidationErrorMessage":"Tu dirección de correo electrónico es demasiado larga"},"collapsible":true,"widgetId":"81412577-b269-4f39-aa2a-21eede97885b","section":"default","category":"neutral","locale":"es-CL","renderMode":"PUBLISH"},{"widgetId":"81412577-b269-4f39-aa2a-21eede97885b","widgetType":"CONTACT","widgetPreset":"contact3","order":2,"section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});