(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-5',
          componentName:'@widget/SUBSCRIBE/bs-subscribe3-subscribe-form',
          props:props,
          context:context,
          contextKey:'context-bs-5',
          radpack:"@widget/SUBSCRIBE/bs-subscribe3-subscribe-form"
        });
      })({"upgradeable":false,"preset":"subscribe3","id":"3278ad15-c233-4a59-907d-08e71982ebe3","isInternalPage":false,"env":"production","websiteId":"0a8a0044-6118-4921-9685-aa429743eeb8","accountId":"8c42f84f-15a5-11eb-81f0-3417ebe73f0e","hasNonCommercePlan":true,"couponToggleHidden":false,"sectionTitle":"Suscribirse","staticContent":{"defaultButtonLabel":"Inscribirse","emailPlaceholderText":"Dirección de correo electrónico","verificationText":"Para avisarnos que realmente eres tú y que deseas recibir nuestros mensajes, haz clic en el enlace incluido en el correo electrónico de confirmación que te acabamos de enviar. Puedes cancelar la suscripción a estos correos electrónicos en cualquier momento.","emailErrorMessage":"Favor de registrar una dirección de correo electrónico verdadera."},"confirmationMessage":"Excelente, confirma ahora tu dirección de correo electrónico","couponConfirmationMessage":"¡Muchas gracias por inscribirte!","description":"Suscríbete para recibir noticias sobre promociones, ofertas y eventos.","couponDescription":"¡Obtén un descuento de 10 % en tu primera compra al inscribirte para recibir nuestro boletín informativo!","inputPlaceholder":"Correo electrónico","subscribeButtonLabel":"Registrarse","couponToggle":true,"background":{"width":"","left":"","height":"","shrinkFit":false,"position":"","alt":"","editedAspectRatio":"","top":"","video":"","image":"\u002F\u002Fimg1.wsimg.com\u002Fisteam\u002Fstock\u002FyrrGkGx","rotation":""},"widgetId":"3278ad15-c233-4a59-907d-08e71982ebe3","section":"default","category":"neutral","locale":"es-CL","renderMode":"PUBLISH"},{"widgetId":"3278ad15-c233-4a59-907d-08e71982ebe3","widgetType":"SUBSCRIBE","widgetPreset":"subscribe3","order":1,"section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Section","groupType":"Banner","websiteThemeOverrides":{},"widgetThemeOverrides":{}});